config/routes.rb
Rails.application.routes.draw do
  root :to => 'articles#index'

  resources :articles, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article.id)
    else
      render :new
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="container">
  <div class="tabs">
    <div class="tabs_item active">
      新着記事一覧
    </div>
    <div class="tabs_item">
      タイムライン
    </div>
  </div>

  <% @articles.each do |article| %>
    <%= link_to article_path(id: article.id) do %>
      <div class="card">
        <div class="card_image">
          <%= image_tag 'eyecatch1.png' %>
        </div>
        <div class="card_content">
        <div class="card_title">
          <%= article.title %>
        </div>
          <div class="card_heart">
            <%= image_tag 'heart.svg' %>
            <span>23</span>
          </div>
          <div class="card_detail">
            <%= image_tag 'default-avatar.png' %>
            <div>
              <p>yuki0108</p>
              <p>2020/4/16</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= link_to new_article_path do %>
    <div class="float_btn">
      <i class="fa fa-plus"></i>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <%= form_with(model: @article, url: articles_path, method: 'post', local: true) do |f| %>
    <div>
      <%= f.label :title, 'タイトル'%>
    </div>
    <div>
      <%= f.text_field :title, class: 'text' %>
    </div>
    <div>
      <%= f.label :content, '内容'%>
    </div>
    <div>
      <%= f.text_area :content %>
    </div>
    <%= f.submit '保存', class: 'btn-primary'%>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
  <h1 class="article_title"><%= @article.title %></h1>
  <div class="article_detail">
    <%= image_tag 'default-avatar.png' %>
    <div>
      <p>cohki0305</p>
      <p>2020/4/16</p>
    </div>
  </div>
  <div class="article_content">
    <%= @article.content %>
  </div>
  <div class="article_heart">
    <%= image_tag 'heart.svg' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
  <header class="header">
      <p class="header_pageTitle">新着記事</p>
      <div class="dropdown">
        <%= image_tag 'default-avatar.png', class: 'header_avatar dropbtn' %>
        <div class="dropdown-content">
          <a href="#">プロフィール</a>
          <a href="#">ログアウト</a>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>